"""empty message

Revision ID: 09df40c3519e
Revises: a707192be4fd
Create Date: 2020-07-18 18:25:27.838136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09df40c3519e'
down_revision = 'a707192be4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('comment', sa.String(length=1024), nullable=True))
    op.add_column('cameras', sa.Column('functional', sa.Boolean(), nullable=True, default=True))
    op.add_column('sites', sa.Column('elev', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('gravel', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('perc_psub', sa.Integer(), nullable=True))
    op.add_column('sites', sa.Column('psub', sa.String(length=50), nullable=True))
    op.add_column('sites', sa.Column('sand', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('silt_clay', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('sm_rocks', sa.Boolean(), nullable=True))
    op.add_column('sites', sa.Column('snag_perch', sa.Integer(), nullable=True))
    op.drop_column('surveys', 'silt_clay')
    op.drop_column('surveys', 'perc_psub')
    op.drop_column('surveys', 'gravel')
    op.drop_column('surveys', 'psub')
    op.drop_column('surveys', 'snag_perch')
    op.drop_column('surveys', 'sm_rocks')
    op.drop_column('surveys', 'sand')
    op.drop_column('surveys', 'elev')
    op.execute("UPDATE sites SET elev = 0.0")
    op.alter_column('sites', 'elev', nullable=False)
    op.execute("UPDATE sites SET gravel = false")
    op.alter_column('sites', 'gravel', nullable=False)
    op.execute("UPDATE sites SET perc_psub = 0")
    op.alter_column('sites', 'perc_psub', nullable=False)
    op.execute("UPDATE sites SET psub = 'FIX ME'")
    op.alter_column('sites', 'psub', nullable=False)
    op.execute("UPDATE sites SET sand = false")
    op.alter_column('sites', 'sand', nullable=False)
    op.execute("UPDATE sites SET silt_clay = false")
    op.alter_column('sites', 'silt_clay', nullable=False)
    op.execute("UPDATE sites SET sm_rocks = false")
    op.alter_column('sites', 'sm_rocks', nullable=False)
    op.execute("UPDATE sites SET snag_perch = 0")
    op.alter_column('sites', 'snag_perch', nullable=False)
    op.execute("UPDATE cameras SET functional = false")
    op.alter_column('cameras', 'functional', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('elev', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('surveys', sa.Column('sand', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('surveys', sa.Column('sm_rocks', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('surveys', sa.Column('snag_perch', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('surveys', sa.Column('psub', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('surveys', sa.Column('gravel', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('surveys', sa.Column('perc_psub', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('surveys', sa.Column('silt_clay', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('sites', 'snag_perch')
    op.drop_column('sites', 'sm_rocks')
    op.drop_column('sites', 'silt_clay')
    op.drop_column('sites', 'sand')
    op.drop_column('sites', 'psub')
    op.drop_column('sites', 'perc_psub')
    op.drop_column('sites', 'gravel')
    op.drop_column('sites', 'elev')
    op.drop_column('cameras', 'functional')
    op.drop_column('cameras', 'comment')
    # ### end Alembic commands ###
