"""predator to species

Revision ID: 12b7acf585d7
Revises: 77cb1a7ef6ce
Create Date: 2021-10-17 13:42:50.271381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12b7acf585d7'
down_revision = '77cb1a7ef6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('predators', 'species')
    op.rename_table('survey_predator', 'survey_species')
    op.rename_table('survey_predator_camera', 'survey_species_camera')

    op.alter_column('species', 'classification', new_column_name='species_type')
    op.alter_column('species', 'predator_type', new_column_name='classification')
    op.alter_column('survey_species', 'predator_id', new_column_name="species_id")
    op.alter_column('survey_species_camera', 'predator_id', new_column_name="species_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('species', 'classification', new_column_name='predator_type')
    op.alter_column('species', 'species_type', new_column_name='classification')
    op.alter_column('survey_species', 'species_id', new_column_name="predator_id")
    op.alter_column('survey_species_camera', 'species_id', new_column_name="predator_id")


    op.rename_table('species', 'predators')
    op.rename_table('survey_species', 'survey_predator')
    op.rename_table('survey_species_camera', 'survey_predator_camera')
    # ### end Alembic commands ###
