"""empty message

Revision ID: 164c23fd697a
Revises: af01f6a07489
Create Date: 2020-10-12 13:01:49.916364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164c23fd697a'
down_revision = 'af01f6a07489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_camera_card', sa.Column('stopped_recording', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_camera_card', 'stopped_recording')
    # ### end Alembic commands ###
