"""pred class and risk columns

Revision ID: 326db3740ff0
Revises: 8ee552faf0b6
Create Date: 2021-08-31 19:03:51.869600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326db3740ff0'
down_revision = '8ee552faf0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predators', sa.Column('classicication', sa.String(length=255), nullable=True))
    op.add_column('predators', sa.Column('risk', sa.String(length=255), nullable=True))
    op.drop_column('predators', 'volatility')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predators', sa.Column('volatility', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('predators', 'risk')
    op.drop_column('predators', 'classicication')
    # ### end Alembic commands ###
