"""empty message

Revision ID: 386a75a7c2a5
Revises: c85506442b46
Create Date: 2020-07-19 16:06:21.831184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386a75a7c2a5'
down_revision = 'c85506442b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('perimeter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'perimeter')
    # ### end Alembic commands ###
