"""empty message

Revision ID: 65fff34f006f
Revises: 386a75a7c2a5
Create Date: 2020-07-19 22:25:30.647866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65fff34f006f'
down_revision = '386a75a7c2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_predator', sa.Column('adult_mort', sa.Boolean(), nullable=True))
    op.add_column('survey_predator', sa.Column('chick_mort', sa.Boolean(), nullable=True))
    op.add_column('survey_predator', sa.Column('nest_dest', sa.Boolean(), nullable=True))
    op.add_column('survey_predator', sa.Column('scat', sa.Boolean(), nullable=True))
    op.add_column('survey_predator', sa.Column('sighting', sa.Boolean(), nullable=True))
    op.drop_column('survey_predator', 'sighting_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_predator', sa.Column('sighting_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('survey_predator', 'sighting')
    op.drop_column('survey_predator', 'scat')
    op.drop_column('survey_predator', 'nest_dest')
    op.drop_column('survey_predator', 'chick_mort')
    op.drop_column('survey_predator', 'adult_mort')
    # ### end Alembic commands ###
