"""inital

Revision ID: 6dc691017acc
Revises: 
Create Date: 2020-07-15 22:52:19.061800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc691017acc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=255), nullable=False),
    sa.Column('predator_type', sa.String(length=255), nullable=False),
    sa.Column('volatility', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('loc_type', sa.String(length=255), nullable=False),
    sa.Column('size_type', sa.String(length=255), nullable=False),
    sa.Column('est_area', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('crew', sa.Integer(), nullable=False),
    sa.Column('time_in', sa.Time(), nullable=False),
    sa.Column('time_out', sa.Time(), nullable=False),
    sa.Column('surveyed', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('ac1', sa.Integer(), nullable=False),
    sa.Column('ac2', sa.Integer(), nullable=False),
    sa.Column('ac3', sa.Integer(), nullable=False),
    sa.Column('egg1', sa.Integer(), nullable=False),
    sa.Column('egg2', sa.Integer(), nullable=False),
    sa.Column('egg3', sa.Integer(), nullable=False),
    sa.Column('chick02', sa.Integer(), nullable=False),
    sa.Column('chick39', sa.Integer(), nullable=False),
    sa.Column('chick1017', sa.Integer(), nullable=False),
    sa.Column('ef1', sa.String(length=3), nullable=False),
    sa.Column('ef2', sa.String(length=3), nullable=False),
    sa.Column('ef3', sa.String(length=3), nullable=False),
    sa.Column('ef4', sa.String(length=3), nullable=False),
    sa.Column('ef_com', sa.String(length=1024), nullable=False),
    sa.Column('elev', sa.Float(), nullable=False),
    sa.Column('scrape', sa.Boolean(), nullable=False),
    sa.Column('snag_perch', sa.Integer(), nullable=False),
    sa.Column('psub', sa.String(length=50), nullable=False),
    sa.Column('perc_psub', sa.Integer(), nullable=False),
    sa.Column('silt_clay', sa.Boolean(), nullable=False),
    sa.Column('sand', sa.Boolean(), nullable=False),
    sa.Column('gravel', sa.Boolean(), nullable=False),
    sa.Column('sm_rocks', sa.Boolean(), nullable=False),
    sa.Column('pveg', sa.String(length=50), nullable=False),
    sa.Column('perc_pveg', sa.Integer(), nullable=False),
    sa.Column('cwdn1', sa.Integer(), nullable=False),
    sa.Column('cwdn2', sa.Integer(), nullable=False),
    sa.Column('cwdn3', sa.Integer(), nullable=False),
    sa.Column('cwdlog', sa.Integer(), nullable=False),
    sa.Column('w_temp', sa.Float(), nullable=True),
    sa.Column('a_temp', sa.Float(), nullable=True),
    sa.Column('perc_dio', sa.Float(), nullable=True),
    sa.Column('sal', sa.Float(), nullable=True),
    sa.Column('sp_condu', sa.Float(), nullable=True),
    sa.Column('condu', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_camera_card',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('card_in_id', sa.Integer(), nullable=True),
    sa.Column('card_out_id', sa.Integer(), nullable=True),
    sa.Column('ch_bat', sa.Boolean(), nullable=False),
    sa.Column('functional', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['card_in_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['card_out_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('survey_id', 'camera_id')
    )
    op.create_table('survey_predator',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('predator_id', sa.Integer(), nullable=False),
    sa.Column('sighting_type', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['predator_id'], ['predators.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('survey_id', 'predator_id', 'sighting_type')
    )
    op.create_table('survey_predator_camera',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('predator_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('scat', sa.Boolean(), nullable=False),
    sa.Column('adult_mort', sa.Boolean(), nullable=False),
    sa.Column('chick_mort', sa.Boolean(), nullable=False),
    sa.Column('nest_dest', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['predator_id'], ['predators.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('survey_id', 'predator_id', 'start', 'end')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_predator_camera')
    op.drop_table('survey_predator')
    op.drop_table('survey_camera_card')
    op.drop_table('surveys')
    op.drop_table('sites')
    op.drop_table('predators')
    op.drop_table('cards')
    op.drop_table('cameras')
    # ### end Alembic commands ###
