"""empty message

Revision ID: 70e4cce20917
Revises: 164c23fd697a
Create Date: 2020-10-12 13:54:59.630199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e4cce20917'
down_revision = '164c23fd697a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_camera_card', sa.Column('started_recording', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_camera_card', 'started_recording')
    # ### end Alembic commands ###
