"""empty message

Revision ID: 7a4b4c396f01
Revises: 65fff34f006f
Create Date: 2020-07-19 23:08:17.788580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4b4c396f01'
down_revision = '65fff34f006f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'ef_com')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('ef_com', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
