"""add plenght and dtoml vars

Revision ID: 8ee552faf0b6
Revises: f90d76ea502c
Create Date: 2021-07-18 21:20:37.803360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee552faf0b6'
down_revision = 'f90d76ea502c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('mainland_distance', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('perimeter_length', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'perimeter_length')
    op.drop_column('sites', 'mainland_distance')
    # ### end Alembic commands ###
