"""empty message

Revision ID: ac99a016453b
Revises: 09df40c3519e
Create Date: 2020-07-19 13:24:31.887552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac99a016453b'
down_revision = '09df40c3519e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('comment', sa.String(length=1024), nullable=True))
    op.add_column('surveys', sa.Column('comment', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'comment')
    op.drop_column('sites', 'comment')
    # ### end Alembic commands ###
