"""empty message

Revision ID: af01f6a07489
Revises: 7a4b4c396f01
Create Date: 2020-07-20 20:15:29.424314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af01f6a07489'
down_revision = '7a4b4c396f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_predator', sa.Column('tracks', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_predator', 'tracks')
    # ### end Alembic commands ###
