"""empty message

Revision ID: c85506442b46
Revises: ac99a016453b
Create Date: 2020-07-19 14:17:01.731873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85506442b46'
down_revision = 'ac99a016453b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'size_type')
    op.add_column('surveys', sa.Column('size_type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'size_type')
    op.add_column('sites', sa.Column('size_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
